version: '3.4'

services:

  redis:
    image: redis
    ports:
      - 6373:6373

  hylo.api.server:
    image: ${DOCKER_REGISTRY-}hyloapiserver
    build:
      context: ../..
      dockerfile: src/api/server/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:80
      HYLO__RESOURCES__PERSISTENCE__PROVIDER: redis 
      HYLO__RESOURCES__PERSISTENCE__PROVIDER__CONNECTIONSTRING: redis
      HYLO__SERVICEBUS__PROVIDER: redis
      HYLO__SERVICEBUS__CONNECTIONSTRING: redis