name: Test .NET

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - 'assets/**'
      - 'deployments/**'
  workflow_call:

env:
  SOLUTION: ./Hylo.sln

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.SOLUTION }}"

      # - name: Test
      #   run: dotnet test "${{ env.SOLUTION }}" --no-restore --verbosity normal"

      # Test "per domain" for ease of readability
      - name: Test File System Database Provider
        run: dotnet test "${{ env.SOLUTION }}" --no-restore --filter "FullyQualifiedName~Providers.FileSystem"

      - name: Test Mongo Database Provider
        run: dotnet test "${{ env.SOLUTION }}" --no-restore --filter "FullyQualifiedName~Providers.Mongo"
        
      - name: Test Redis Database Provider
        run: dotnet test "${{ env.SOLUTION }}" --no-restore --filter "FullyQualifiedName~Providers.Mongo"

      # ...